build_base_image:
  stage: build
  variables:
    http_proxy: "https://proxyout.lanl.gov:8080"
    https_proxy: "https://proxyout.lanl.gov:8080"
    no_proxy: "localhost,127.0.0.1,*.lanl.gov,lanl.gov"
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    # add certificates:
    - apk add --no-cache ca-certificates
    - update-ca-certificates  
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg http_proxy=$http_proxy
      --build-arg https_proxy=$https_proxy
      --build-arg no_proxy=$no_proxy
      --dockerfile "${CI_PROJECT_DIR}/base-ubuntu/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"