# ----------------------------------------------------------------------
# Debian baseOS docker container to use with ELM/CTSM builds
# ----------------------------------------------------------------------

FROM ubuntu:jammy

# Set a few variables that can be used to control the docker build
ARG HDF5_VERSION=1.14.6
ARG NETCDF_VERSION=4.9.2
ARG NETCDF_FORTRAN_VERSION=4.6.2

# set path variables
ENV PATH=/usr/local/netcdf/bin:/usr/local/bin:/usr/local/hdf5/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/netcdf/lib:/usr/local/hdf5/lib:$LD_LIBRARY_PATH

# Update the system and install initial dependencies
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone \
    && apt-get update -y \
    && apt-get upgrade -y && apt-get install -y tzdata \
    && apt-get install -y \
    cmake \
    cpp \
    git \
    gcc \
    gfortran \
    expat \
    subversion \
    bzip2 \
    unzip \
    libgmp3-dev \
    m4 \
    autoconf \
    automake \
    libtool \
    wget \
    libcurl4-openssl-dev \
    zlib1g-dev \
    libncurses5-dev \
    csh \
    liblapack-dev \
    libblas-dev \
    libevent-dev \
    libffi7 \
    libffi-dev \
    libhwloc-dev \
    libxml-libxml-perl \
    libxml2-utils \
    libxml2 \
    libxml2-dev \
    libswitch-perl \
    vim \
    libudunits2-0 \
    libudunits2-dev \
    udunits-bin \
    python3 \
    python3-dev \
    python3-pip \
    python-is-python3 \
    apt-utils \
    ftp \
    apt-transport-https \
    libssl-dev \
    openssl \
    libncurses5-dev \
    gsl-bin \
    libgsl-dev \
    flex \
    nco \
    ncview \
    locales \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean all \
    && apt autoremove


## Set default locale for the environment
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

## HDF5 - use alternative source since main HDF5 source doesnt have useful download links
#https://support.hdfgroup.org/ftp/HDF5/releases/
RUN cd / \
    && mkdir -p /usr/local/hdf5 \
    && wget https://support.hdfgroup.org/releases/hdf5/v1_14/v1_14_6/downloads/hdf5-${HDF5_VERSION}.tar.gz \
    && tar -zxvf hdf5-${HDF5_VERSION}.tar.gz \
    && cd hdf5-${HDF5_VERSION} \
    && CPPFLAGS="-fPIC -O2" ./configure --enable-fortran --prefix=/usr/local/hdf5 \
    && make \
    && make install \
    && cd / \
    && rm -r hdf5-${HDF5_VERSION} \
    && rm hdf5-${HDF5_VERSION}.tar.gz

# NO PNETCDF NEEDED!!

## netCDF
RUN cd / \
    && mkdir -p /usr/local/netcdf \
    && wget https://downloads.unidata.ucar.edu/netcdf-c/${NETCDF_VERSION}/netcdf-c-${NETCDF_VERSION}.tar.gz \
    && tar -zxvf netcdf-c-${NETCDF_VERSION}.tar.gz \
    && cd netcdf-c-${NETCDF_VERSION} \
    && export H5DIR=/usr/local/hdf5 \
    && export NCDIR=/usr/local/netcdf \
    && CPPFLAGS="-I${H5DIR}/include -fPIC -O2" LDFLAGS="-L${H5DIR}/lib" ./configure --prefix=${NCDIR} \
    && make \
    && make check \
    && make install \
    && cd / \
    && rm -r netcdf-c-${NETCDF_VERSION} \
    && rm netcdf-c-${NETCDF_VERSION}.tar.gz \
    && wget https://downloads.unidata.ucar.edu/netcdf-fortran/${NETCDF_FORTRAN_VERSION}/netcdf-fortran-${NETCDF_FORTRAN_VERSION}.tar.gz \
    && tar -zxvf netcdf-fortran-${NETCDF_FORTRAN_VERSION}.tar.gz \
    && cd netcdf-fortran-${NETCDF_FORTRAN_VERSION} \
    && export NCDIR=/usr/local/netcdf \
    && export NFDIR=/usr/local/netcdf \
    && CPPFLAGS="-I${NCDIR}/include -I${H5DIR}/include -fPIC -O2" LDFLAGS="-L${NCDIR}/lib -L${H5DIR}/lib" ./configure --prefix=${NFDIR} \
    && make \
    && make install \
    && cd / \
    && rm -r netcdf-fortran-${NETCDF_FORTRAN_VERSION} \
    && rm netcdf-fortran-${NETCDF_FORTRAN_VERSION}.tar.gz

# Set some environment variables
ENV LD_LIBRARY_PATH=/usr/lib:/usr/lib/aarch64-linux-gnu
ENV NETCDF_C_PATH=/usr
ENV NETCDF_FORTRAN_PATH=/usr

### EOF
