name: Build and Push Docker Images

on:
  push:
    branches: '**'

env:
  REGISTRY: docker.io
  IMAGE_OWNER: rfiorella

jobs: 
  build-images:
    matrix: [ ubuntu-arm64-24.04, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
  steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push base ubuntu image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./base-ubuntu/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER}}/model-containers:base-ubuntu-latest





